### PR TITLE
treadmill/runtime_configure: Global Configuration Using Single treadmill.toml with option to overwrite using cli or environment variables

### PR DESCRIPTION
**Pull request by charles37**
This pull request introduces a unified configuration system for the Treadmill project using Figment (in response to #6). The primary objective is to centralize and standardize configuration management across various components of the project.

**TOML Configuration File:**
   - Created a `treadmill.toml` file in the project root with configuration sections for each component.
   - Added default values and structure for each component's configuration.

#### How to Test
1. **Global Config File:**
   - Run each component using the default `treadmill.toml` file:
     ```bash
     cargo run --bin tml-switchboard
     cargo run --bin tml-mock-supervisor
     cargo run --bin tml-puppet
     ```

2. **Custom Config File:**
   - Specify a custom configuration file via command-line arguments:
     ```bash
     cargo run --bin tml-switchboard -- --config custom_config.toml
     ```

3. **Environment Variables:**
   - Override specific settings using environment variables:
     ```bash
     TREADMILL_SWITCHBOARD__DATABASE__PORT=5433 cargo run --bin tml-switchboard
     ```

Notes for discussion:
I left in the mock supervisor:
```
the following required arguments were not provided:
  --config-file <CONFIG_FILE>
  --puppet-binary <PUPPET_BINARY>
  ```
I can easily remove the need for a config file because its already redundant, but wanted to discuss to you guys having to put the puppet binary in the config file.

I left the config_file variables in switchboard as well, but can easily remove these as well.

I have left a lot of lingering dead code and unneeded imports, I will clean these up, but wanted to get this out for discussion before our meeting today

### CODE REVIEW

**Comment by max-cura** [comment]
A couple comments:
1. Not sure if global configuration makes sense here, since outside of testing, I don't think we'll ever see multiple components running on the same machine. My view is that having one configuration file per binary is better.
2. It would be nice to have a way to specify e.g. `TREADMILL_CONFIG=path/to/config.toml` as an env var.

As an aside to the last two, I'm not sure how I feel about having hardcoded default config paths, or at least hardcoded relative paths as defaults, or even if we should have a default path in the first place.
A bit of bikeshedding: would `TREADMILL_` or `TML_` be a better prefix for the env vars?

**Comment by charles37** [comment]
> A couple comments:
> 
>     1. Not sure if global configuration makes sense here, since outside of testing, I don't think we'll ever see multiple components running on the same machine. My view is that having one configuration file per binary is better.
> 
>     2. It would be nice to have a way to specify e.g. `TREADMILL_CONFIG=path/to/config.toml` as an env var.
> 
> 
> As an aside to the latter, I'm not sure how I feel about having hardcoded default config paths, or at least hardcoded relative paths as defaults, or even if we should have a default path in the first place. A bit of bikeshedding: would `TREADMILL_` or `TML_` be a better prefix for the env vars?


1. If this is how we would prefer to do I could  make each config a Maybe type, and then have each read from its own file.

```
#[derive(Debug, Deserialize, Clone)]
pub struct TreadmillConfig {
    pub switchboard: Option<SwitchboardConfig>,
    pub supervisor: Option<SupervisorConfig>,
    pub puppet: Option<PuppetConfig>,
    pub connector: Option<ConnectorConfig>,
}
```
2. This can already be added, I'll work on this.

**Comment by max-cura** [comment]
> If this is how we would prefer to do I could  make each config a Maybe type, and then have each read from its own file.
> 
> ```
> #[derive(Debug, Deserialize, Clone)]
> pub struct TreadmillConfig {
>     pub switchboard: Option<SwitchboardConfig>,
>     pub supervisor: Option<SupervisorConfig>,
>     pub puppet: Option<PuppetConfig>,
>     pub connector: Option<ConnectorConfig>,
> }
> ```

If only one field is populated and accessed, why have everything in a central struct?

**Comment by lschuermann** [comment]
I agree with @max-cura that there is no need for a unified configuration file across all of our components.

I think there is some value in having standardized configuration formats within the same type of component: for instance, all supervisors can share common configuration sections (and types) for per-connector options. That also already exists---up to some degree---with the current architecture.

I think that after reworking this to use individual configs per component, this should be good to go.

**Comment by lschuermann** [comment]
@charles37 Should we close this PR in favor of a follow-up that integrates figment in a way that's closer to what the Switchboard does?

**Pull request closed without merging**
